# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:3.4.2
    restart: always
    environment:
        # provide your credentials here
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/data/log
    ports:
      - "27017:27017"
    volumes:
        # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      - ./data/db:/data/db
      - ./data/log:/data/log
    # no --auth is needed here as presence of username and password add this option automatically
    command: mongod

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example